[package]
name = "markdeck"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = "4.5.54"
markdown = "1.0.0"
ratatui = { version = "0.30.0", default-features = false, features = [
  "crossterm",
] }
