[package]
name = "markdeck"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.30.0", features = ["crossterm"] }
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
markdown = "1.0.0"
tui-scrollview = "0.6.2"

[dev-dependencies]
tempfile = "3"
